### ISSUE TITLE
When using long release times, attack level does not restart

### ISSUE THREAD

**Issue by felipegaspari** [mo-thunderz/adsr#2]
When using long release times, after a note off attack level does not start from 0, but from the current level... I don't know if it is a feature or what, but would be great to allow the attack to start from 0. This is my code:

void ADSR1() {

  tADSR1 = micros();

  ADSR1Level[0] = adsr1_voice_0.getWave(tADSR1);
  ADSR1Level[1] = adsr1_voice_1.getWave(tADSR1);

  if (noteEnd[0] == 1) {
    adsr1_voice_0.noteOff(tADSR1 - 1);
  } else if (noteStart[0] == 1) {
    adsr1_voice_0.noteOff(tADSR1 - 1);
    adsr1_voice_0.setAttack(ADSR1_attack);
    adsr1_voice_0.setDecay(ADSR1_decay);
    adsr1_voice_0.setRelease(ADSR1_release);
    adsr1_voice_0.noteOn(tADSR1);
  }
}

**Comment by mo-thunderz** [comment]
Hello Felipe,

thank you for reaching out. Yes, I indeed deliberately start a new trigger
at the current value. The main reason is that when you reset the value to 0
you can get a sharp click as a result because of the transient generated. I
am currently on PTO and cannot really test the code, but I have implemented
a function to have the ADSR reset whenever a new trigger is received. Can
you download the library and check if it works for you now? Just run in the
setup:
Class_name.setResetAttack(true);

As said, I could not test it, but it should work. If there is anything
still missing, please let me know.
https://github.com/mo-thunderz/adsr

Cheers,
Sander

Op za 13 aug. 2022 om 18:12 schreef felipegaspari ***@***.***

**Comment by felipegaspari** [comment]
That was fast! Works perfectly, thanks! Enjoy your time off!
